Vagrant.configure("2") do |config|

  config.vm.provider :libvirt do |libvirt|
    libvirt.disk_bus       = "virtio"
    libvirt.driver         = "kvm"
    #libvirt.graphics_type  = "spice"
    libvirt.graphics_type  = "vnc"
    libvirt.graphics_port  = "5910"
    libvirt.graphics_ip    = "0.0.0.0"
    libvirt.nic_model_type = "virtio"
    libvirt.sound_type     = "ich6"
    libvirt.video_type     = "qxl"
#    libvirt.mgmt_attach    = false
    libvirt.input :type => "tablet", :bus => "usb"

    libvirt.channel :type  => 'spicevmc', :target_name => 'com.redhat.spice.0',     :target_type => 'virtio'
    libvirt.channel :type  => 'unix',     :target_name => 'org.qemu.guest_agent.0', :target_type => 'virtio'
    libvirt.random  :model => 'random'
    libvirt.memory         = 2048
  end

  config.vm.box = "vargiuscuola/my_ubuntu-20.04-server-amd64"
  config.vm.network :public_network,
    ip: "172.25.100.10",
    netmask: "255.255.0.0",
    dev: "vm-lan-br",
    network_name: "bridged-lan",
    bridge: "vm-lan-br",
    type: "bridge",
    mode: "bridge"

  # Disable NFS sharing (==> default: Mounting NFS shared folders...)
  config.vm.synced_folder ".", "/vagrant", type: "nfs", disabled: true
end
